backbone: smaat
backbone_ckpt: null
batch_size: 6
ckpt_milestone: Exps/basic_exps/Diffsmaat_sevir_smaat_rootcause_fix_traincond_100k/checkpoints/ckpt-208341.pt
dataset: sevir
det_loss_weight: 0.5
diff_loss_weight: 0.5
diff_teacher_forcing_ratio: 1.0
early_stop: 10
ema_rate: 0.95
epochs: 20
eval: true
eval_conditioning_mode: autoregressive
eval_max_batches: null
eval_residual_scales: null
eval_split: test
exp_dir: basic_exps
exp_note: null
frames_in: 5
frames_out: 20
freeze_backbone: false
grad_acc_step: 1
img_channel: 1
img_size: 128
l2_norm: 0.0
lr: 0.0001
lr_beta1: 0.9
lr_beta2: 0.95
max_checkpoints: 3
mixed_precision: 'no'
num_workers: 4
residual_scale: 0.25
scheduler: cosine
seed: 0
seq_len: 25
skip_eval_image_save: true
smaat_loss: mse
smaat_teacher_forcing: 0.5
train_sampling_timesteps: 8
training_steps: 200000
use_diff: true
wandb_state: disabled
warmup_steps: 1000
