backbone: smaat
batch_size: 6
ckpt_milestone: Exps/basic_exps/Singlesmaat_sevir_smaat_tf07_charb/checkpoints/ckpt-208341.pt
dataset: sevir
early_stop: 10
ema_rate: 0.95
epochs: 20
eval: true
exp_dir: basic_exps
exp_note: smaat_tf07_charb
frames_in: 5
frames_out: 20
grad_acc_step: 1
img_channel: 1
img_size: 128
l2_norm: 0.0
lr: 0.0001
lr_beta1: 0.9
lr_beta2: 0.95
mixed_precision: 'no'
num_workers: 4
scheduler: cosine
seed: 0
seq_len: 25
smaat_loss: charbonnier
smaat_teacher_forcing: 0.7
training_steps: 200000
use_diff: false
wandb_state: disabled
warmup_steps: 1000
